# Nome do seu workflow
name: Monitor Diário Oficial TCE-CE

# Define quando o workflow será executado
on:
  # Permite que você execute este workflow manualmente na aba Actions
  workflow_dispatch:

  # Agenda a execução automática
  schedule:
    # Executa todos os dias da semana (de segunda a sexta) às 10:00 no horário de Brasília (13:00 UTC)
    # Formato: Minuto Hora Dia(mês) Mês Dia(semana)
    - cron: '30 18 * * 1-5'

# Define os trabalhos (jobs) a serem executados
jobs:
  build:
    # O tipo de máquina virtual para executar o job
    runs-on: ubuntu-latest

    # Passos que compõem o job
    steps:
      # 1. Baixa o código do seu repositório para a máquina virtual
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Configura o ambiente Python na versão 3.10
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # 3. Instala as dependências listadas no arquivo requirements.txt
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4. Executa o seu script Python
      - name: Run Python script
        # Passa os Secrets para o script como variáveis de ambiente
        env:
          EMAIL_SENDER: ${{ secrets.EMAIL_SENDER }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          EMAIL_RECIPIENTS: ${{ secrets.EMAIL_RECIPIENTS }}
        run: python monitor_tce.py
