# .github/workflows/run_scraper.yml
name: Baixar Diário Oficial TCE-CE

on:
  workflow_dispatch:
  schedule:
    - cron: '0 9 * * *'

jobs:
  build-and-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do Repositório
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalar Firefox e dependências
        uses: browser-actions/setup-firefox@v1

      - name: Instalar dependências Python
        run: pip install -r requirements.txt

      - name: Executar o script de download
        run: python DOTCE-CE_VGH.py # ou o nome do seu arquivo .py

      - name: Commit e Push do Diário Oficial
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Diário Oficial baixado em $(date -u --iso-8601=seconds)"
          file_pattern: "*.pdf"
          commit_user_name: GitHub Actions Bot
          commit_user_email: actions@github.com
          commit_author: GitHub Actions Bot <actions@github.com>
